WIP: travis stuff

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,7 +1,7 @@
 # R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
 language: r
 
-dist: trusty
+dist: xenial
 sudo: false
 warnings_are_errors: false # setting this false b/c of rcpp attribute error
 
@@ -16,8 +16,73 @@ before_install:
   - rm travis_helpers.sh
   - start_xvfb ;
   - v8_install ;
+  - Rscript -e 'install.packages("devtools")'
   - Rscript -e 'install.packages("rsvd")'
   - Rscript -e 'install.packages("magic")'
   - Rscript -e 'install.packages(c("psych","colormap"))'
   - Rscript -e 'install.packages("RcppEigen")'
   - gh_binary_install  stnava/ITKR ANTsX/ANTsRCore ANTsX/ANTsR
+  - git clone https://github.com/ANTsX/ANTsRNet.git
+  - R CMD INSTALL ANTsRNet
+
+install:
+  - echo "skip this"
+
+script:
+  - x=`export_clang_cxx`; eval ${x}
+  - travis_wait 100 R CMD build ${R_BUILD_ARGS} .
+  - rm -f travis_wait*.log
+  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
+  - ls
+  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+  - rm -f travis_wait*.log
+  - if [[ $CHECK_RET -ne 0 ]];
+    then
+      echo "R CMD check failed";
+      check_fail;
+      dump_logs;
+      travis_terminate 1;
+    fi
+  - check_warnings
+
+
+after_failure:
+  - dump_logs
+
+after_success:
+  - dump_logs
+  - ls
+  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1);
+  - PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
+  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
+      PKG_FILE_NAME=$(ls -1t *.tgz | head -n  1);
+      PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
+    fi
+  - mv ${PKG_FILE_NAME} ${PKG_TARBALL_WITH_R} ;
+  - PKG_FILE_NAME=${PKG_TARBALL_WITH_R}
+
+notifications:
+  email:
+    recipients:
+    - stnava@gmail.com
+    on_success: change
+    on_failure: always
+
+# so no overwrite of linux build
+before_deploy:
+  - if [ "$TRAVIS_OS_NAME" = "osx" ];
+    then
+      rm -f *.tar.gz;
+    fi
+
+deploy:
+  - provider: releases
+    api_key:
+      secure: VevZHK5WDwd2mFSrF3+b2jTRzImb6juOgewcOvZ8LJ2S70khn64Kx4+JGUvk5miKWVbKnHIhPxOJY50muO9sT15ApP+HFZYpiVpx4l/hEypk9zmJD+f+ERuN7j8elCzUZqet3v77XD+pBcYMxFARew4gGDkG2LO5casij0YNiyQ=
+    file: ${PKG_FILE_NAME}
+    skip_cleanup: true
+    on:
+      tags: true
+      repo: ${gh_user}/${PROJ_DIR}
+      all_branches: true
+      condition: "${gh_user} = ANTsX"
